language: go

os:
    - linux
    - osx
    - windows

matrix:
    allow_failures:
        - os: windows

go:
    - "1.8"
    - "1.9"

before_script:
    - make install_dependencies 
    
script:
    - make test
    - make vet
    - make fmt
